USE DepositoVehicular_DB
GO

CREATE TABLE [dbo].[Inasistencias](
[Id] [int] IDENTITY(1,1) NOT NULL,
[IdDeposito] [int] NOT NULL,
[IdIncidente] [int] NOT NULL,
[Anotacion] [nvarchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
FOREIGN KEY([IdDeposito]) REFERENCES [CatDepositoVehicular](Id),
FOREIGN KEY([IdIncidente]) REFERENCES [Incidentes](Id)
) ON [PRIMARY]
