USE [DepositoVehicular_DB]
GO
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Aguascalientes')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Baja California')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Baja California Sur')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Campeche')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Chiapas')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Chihuahua')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Ciudad de México')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Coahuila')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Colima')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Durango')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Estado de México')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Guanajuato')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Guerrero')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Hidalgo')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Jalisco')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Michoacán')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Morelos')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Nayarit')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Nuevo León')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Oaxaca')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Puebla')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Querétaro')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Quintana Roo')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('San Luis Potosí')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Sinaloa')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Sonora')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Tabasco')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Tamaulipas')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Tlaxcala')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Veracruz')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Yucatán')
INSERT [dbo].[Estados] ([dbo].[Estado]) VALUES('Zacatecas ')

GO