USE [DepositoVehicular_DB]
GO
SET IDENTITY_INSERT [dbo].[CatDepositoVehicular] ON 
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (6, N'MANIOBRAS Y SERVICIOS DE GRÚAS CONTINENTAL S.A. DE C.V.', N'TANIA FLORES MONTIEL', N'correo', N'TANIA FLORES MONTIEL', N'2221324360', N'LOTE 1 MANZANA 12 CALLE 1° DE ENERO LA CUCHILLA XONACATEPEC PUEBLA. C.P. 72229  2 DE ABRIL 16 VILLA GUADALUPE 72229 PUEBLA PUE.', 1, N'https://maps.app.goo.gl/S19cu8Cd57PSCofP6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (7, N'JOSÉ LUIS CARRERA PÉREZ – GRÚAS GAP', N'JOSÉ LUIS CARRERA PÉREZ', N'correo', N'JOSÉ LUIS CARRERA PÉREZ', N'2227508158, 2226111074', N'CARRIL SAN LORENZO NO. 804, COLONIA SAN LORENZO CHACHAPA, JUNTA AUXILIAR CHACHAPA, MUNICIPIO DE AMOZOC DE MOTA, PUEBLA. C.P. 72990', 1, N'https://maps.app.goo.gl/AEZ19WijXvpy2Y8p6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (9, N'GRÚAS DOAMA S.A. DE C.V.', N'KARINA LEON DURAN', N'correo', N'KARINA LEON DURAN', N'222 7063010', N'CALLE CAMINO A SAN MIGUEL ESPEJO NO. 340 A COLONIA SANTA MARÍA XONACATEPEC PUEBLA.', 1, N'https://maps.app.goo.gl/ERTkPhsFqorZRMAX6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (10, N'DESPLAZAMIENTO ESPECIALIZADO EN ASISTENCIA S.A. DE C.V.', N'VICTOR SUÁREZ SÁNCHEZ', N'correo', N'VICTOR SUÁREZ SÁNCHEZ', N'2222490300,2222490301,2222490302, 2226514094', N'CAMINO ANTIGUÓ A SAN MIGUEL ESPEJO KM. 6.5, PARQUE INDUSTRIAL CHACHAPA, MUNICIPIO DE AMOZOC.', 1, N'https://maps.app.goo.gl/3hGbLSxv2T9AJxeh7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (11, N'GERARDO CIELO JIMÉNEZ – GRÚAS CIELO', N'GERARDO CIELO JIMENEZ', N'correo', N'GERARDO CIELO JIMENEZ', N'2221150941, 5519682264', N'CALLE RICARDO FLORES MAGÓN NO. 71 Y 419, JUNTA AUXILIAR DE SAN AGUSTÍN CALVARIO, MUNICIPIO DE SAN PEDRO CHOLULA, PUEBLA.', 1, N'https://maps.app.goo.gl/6yjjELMCCvZRQqWa6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (12, N'GRÚAS EXPRESS DE PUEBLA S.A. DE C.V', N'ALONDRA GARCÍA HERNÁNDEZ', N'correo', N'ALONDRA GARCÍA HERNÁNDEZ', N'2227081384, 2223298170', N'AVENIDA SAN LORENZO NO. 804-A, ENTRE PRIVADA EL CIELO Y VÍA DEL FERROCARRIL, COLONIA SAN LORENZO CHACHAPA, AMOZOC DE MOTA PUEBLA.', 1, N'https://maps.app.goo.gl/rbuSmMLdP2v1Y9Y97', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (13, N'GERARDO CIELO GARCÍA – GRÚAS GARCÍA', N'GERARDO CIELO GARCÍA', N'correo', N'GERARDO CIELO GARCÍA', N'2227219261, 2295192954', N'CALLE RICARDO FLORES MAGÓN NO. 417, SAN AGUSTIN CALVARIO, MUNICIPIO DE SAN PEDRO CHOLULA, PUEBLA. CALLE ALVARO OBREGÓN NO. 1111, SANTA MARÍA TONANZINTLA, SAN ANDRÉS CHOLULA', 1, N'https://maps.app.goo.gl/tbejh7tgfrXFPWzr6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (14, N'MARÍA DE LOS ÁNGELES MORENO SÁNCHEZ - EBEN EZER', N'MARÍA DE LOS ÁNGELES MORENO SÁNCHEZ', N'correo', N'MARÍA DE LOS ÁNGELES MORENO SÁNCHEZ', N'2227065784', N'CALLE CHAMIZAL NO. 275, LOCALIDAD SAN FRANCISCO OCOTLÁN, MUNICIPIO DE CORONANGO, PUEBLA. C.P. 72680', 1, N'https://maps.app.goo.gl/Md7a2jKpf4HrVD6b9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (15, N'RAVLA S.A. DE C.V', N'ARTURO LEAL LARA', N'correo', N'ARTURO LEAL LARA', N'22299985', N'PARCELA NÚMERO 283/Z12 P4/5 DEL EJIDO DE SAN FRANCISCO TOTIMEHUACÁN, PUEBLA. CERRADA SIN NOMBRE AVENIDA LIBERTAD S/N SAN FRANCISCO TOTIMEHUACÁN, PUEBLA', 1, N'https://maps.app.goo.gl/ugfgzu3kfgRjqka39', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (16, N'GRÚAS CRONO S.A. DE C.V.', N'ANGEL ITAI FABIOLA MUÑOZ GUADALUPE HERNANDEZ', N'correo', N'ANGEL ITAI FABIOLA MUÑOZ GUADALUPE HERNANDEZ', N'N/A', N'BOULEVARD CHOLULA-HUEJOTZINGO NO. KM 95.5 Y/O 99.5, JUNTA AUXILIAR SAN SEBASTIÁN TEPALCATEPEC, SAN PEDRO CHOLULA, PUEBLA.', 1, N'https://maps.app.goo.gl/EjAeTnYtjoL4VYVz7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (17, N'TRANSPORTES TERRESTRES ROSMAG S.A. DE C.V.', N'GERARDO ANGEL RODRIGUEZ SANCHEZ', N'correo', N'GERARDO ANGEL RODRIGUEZ SANCHEZ', N'2229025107, 2225357743', N'25 NORTE 2519 COLONIA LAS CUARTILLAS, PUEBLA', 1, N'https://maps.app.goo.gl/W1xBrG758zyg46Hw5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (18, N'MANIOBRAS Y SERVICIOS DE GRÚAS AYA S.A. DE C.V.', N'TANIA FLORES MONTIEL', N'correo', N'TANIA FLORES MONTIEL', N'22248771', N'CALLE 2 DE ABRIL 700, COLONIA VILLA GUADALUPE XONACATEPEC, PUEBLA, PUE.', 1, N'https://maps.app.goo.gl/GEuvCsNQm52KMi9cA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (19, N'ARRASTRES NACIONALES EN SINIESTROS S.A. DE C.V.', N'ALFREDO RODRIGUEZ VICTORIA', N'correo', N'ALFREDO RODRIGUEZ VICTORIA', N'22299322', N'CAMINO A SAN MIGUEL ESPEJO KM 6.5 PARQUE INDUSTRIAL CHACHAPA, PUEBLA.', 1, N'https://maps.app.goo.gl/eCVPnY6yCPwKUag17', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (20, N'GRUPO DE GRÚAS UNIDAS DE ESTATALES S.A. DE C.V.', N'ERASMO HECTOR ROJAS DIAZ', N'correo', N'ERASMO HECTOR ROJAS DIAZ', N'22201404', N'CAMINO REAL A TLAXCALA 62 C, SAN JERONIMO CALERAS, PUEBLA', 1, N'https://maps.app.goo.gl/WXUovbS78DuxWQrG6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (21, N'JOSÉ LUIS CARRERA PÉREZ – GRÚAS GAP', N'JOSÉ LUIS CARRERA PÉREZ', N'correo', N'JOSÉ LUIS CARRERA PÉREZ', N'2227508158', N'CARRIL SAN LORENZO NO. 804, COLONIA SAN LORENZO CHACHAPA, JUNTA AUXILIAR CHACHAPA, MUNICIPIO DE AMOZOC DE MOTA, PUEBLA. C.P. 72990', 2, N'https://maps.app.goo.gl/AEZ19WijXvpy2Y8p6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (22, N'MARTINIANO MENDEZ ROJAS "GRÚAS SAN ANDRES', N'MARTINIANO MENDEZ ROJAS', N'correo', N'MARTINIANO MENDEZ ROJAS', N'2223404059, 2211952444,2223333546', N'PARCELA NO. 1075 Z-1 P 5/7 DEL PARAJE DENOMINADO ESTREMEÑO DEL EJIDO DE AMOZOC, MUNICIPIO DE AMOZOC, PUEBLA', 2, N'https://maps.app.goo.gl/yBu6YbZQE7uyxQx57', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (23, N'ARRASTRES NACIONALES EN SINIESTROS S.A. DE C.V.', N'ALFREDO RODRIGUEZ VICTORIA', N'correo', N'ALFREDO RODRIGUEZ VICTORIA', N'22299322', N'CAMINO A SAN MIGUEL ESPEJO KM 6.5 PARQUE INDUSTRIAL CHACHAPA, PUEBLA.', 2, N'https://maps.app.goo.gl/eCVPnY6yCPwKUag17', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (24, N'SERVICO VILLAGRÁN DE PUEBLA, S.A. DE C.V.', N'VÍCTOR HUGO VILLAGRÁN ARROYO', N'correo', N'VÍCTOR HUGO VILLAGRÁN ARROYO', N'2222888800', N'CARRIL DE SAN CRISTÓBAL  NO. 87, COLONIA SAN LORENZO CHACHAPA, SAN SALVADOR CHACHAPA, AMOZOC,PUEBLA, C.P.72990', 2, N'https://maps.app.goo.gl/UEEriWYMMkt1C2rE8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (25, N'GRÚAS Y MANIOBRAS DE PUEBLA, S.A. DE C.V.', N'GUMERSINDO LOAIZA MORALES', N'correo', N'GUMERSINDO LOAIZA MORALES', N'2221684849', N'KM 003+90 DE LA CARRETERA FEDERAL AMOZOC-ORIENTAL, AMOZOC, PUEBLA.', 2, N'https://maps.app.goo.gl/HB58BPCM5CAjS7xq5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (26, N'GRÚAS EXPRESS DE PUEBLA S.A. DE C.V', N'ALONDRA GARCÍA HERNÁNDEZ', N'correo', N'ALONDRA GARCÍA HERNÁNDEZ', N'2227081384, 2223298170', N'AVENIDA SAN LORENZO NO. 804-A, ENTRE PRIVADA EL CIELO Y VÍA DEL FERROCARRIL, COLONIA SAN LORENZO CHACHAPA, AMOZOC DE MOTA PUEBLA.', 2, N'https://maps.app.goo.gl/rbuSmMLdP2v1Y9Y97', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (27, N'JESÚS FUENTES PERALTA', N'JESUS FUENTES PERALTA', N'correo', N'JESUS FUENTES PERALTA', N'2491538388, 2494224826', N'CALLE 3 ORIENTE NO. 1804, ENTRE 16 SUR Y CARRETERA TECAMACHALCO-TOCHTEPEC, BARRIO DE SAN JUAN TECAMACHALCO, PUEBLA.', 3, N'https://maps.app.goo.gl/nghb6MkWeTQpQZuQA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (28, N'KARINA CAMPOS MUÑOZ - GRÚAS PERCAM', N'KARINA CAMPOS MUÑOZ', N'correo', N'KARINA CAMPOS MUÑOZ', N'2491710903, 2491167518', N'CARRETERA ESTATAL ALSESECA XOCHIMILCO, CALLE 10 PONIENTE 3103, ALSESECA, PUEBLA.', 3, N'https://maps.app.goo.gl/rhvBfoxzYc2JgtLQ6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (29, N'ARMANDO FUENTES PERALTA - GRÚAS JUNZA', N'ARMANDO FUENTES PERALTA', N'correo', N'ARMANDO FUENTES PERALTA', N'2224288204', N'CARRETERA PUEBLA-XALAPA MAZAPILTEPEC DE JUÁREZ, PUEBLA.', 3, N'https://maps.app.goo.gl/a4LCQoBy4389WujB7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (30, N'GRÚAS ACATZINGO S.A. DE C.V.', N'MIGUEL ÁNGEL ALDUCIN BAYLON', N'correo', N'MIGUEL ÁNGEL ALDUCIN BAYLON', N'2494241388, 2491000666, 018008363313', N'LIBRAMIENTO VÍA JALAPA KM. 187, BARRIO DE JESÚS DE ALONSO, ACATZINGO DE HIDALGO, PUEBLA. C.P. 75150. C. ANTIGUO ACATZINGO EX RANCHO SAN MARCOS, ACATZINGO, PUEBLA.', 3, N'https://maps.app.goo.gl/jMCUWZ8gMRx6kfMH6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (32, N'AUTO TRASLADOS FORZA S.A. DE C.V.', N'CARLOS OMAR RUÍZ MEDINA', N'correo', N'CARLOS OMAR RUÍZ MEDINA', N'5513687870', N'CALLE JOSÉ MARÍA MORELOS S/N COLONIA SAN FRANCISCO OCOTLÁN CORONANGO PUEBLA.', 4, N'https://maps.app.goo.gl/kgczcL3oXbHojzjj6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (33, N'GRÚAS CRONO S.A. DE C.V.', N'ANGEL ITAI FABIOLA MUÑOZ GUADALUPE HERNANDEZ', N'correo', N'ANGEL ITAI FABIOLA MUÑOZ GUADALUPE HERNANDEZ', N'2212039710, 22261669', N'BOULEVARD CHOLULA-HUEJOTZINGO NO. KM 95.5 Y/O 99.5, JUNTA AUXILIAR SAN SEBASTIÁN TEPALCATEPEC, SAN PEDRO CHOLULA, PUEBLA.', 4, N'https://maps.app.goo.gl/EjAeTnYtjoL4VYVz7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (34, N'GERARDO CIELO GARCÍA – GRÚAS GARCÍA', N'GERARDO CIELO GARCÍA', N'correo', N'GERARDO CIELO GARCÍA', N'2227219261, 2295192954', N'CALLE RICARDO FLORES MAGÓN NO. 417, SAN AGUSTIN CALVARIO, MUNICIPIO DE SAN PEDRO CHOLULA, PUEBLA. CALLE ALVARO OBREGÓN NO. 1111, SANTA MARÍA TONANZINTLA, SAN ANDRÉS CHOLULA', 4, N'https://maps.app.goo.gl/uypCTBCJQ1oLFyaV7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (35, N'GERARDO CIELO JIMÉNEZ – GRÚAS CIELO', N'GERARDO CIELO JIMENEZ', N'correo', N'GERARDO CIELO JIMENEZ', N'2221150941, 5519682264', N'CALLE RICARDO FLORES MAGÓN NO. 71 Y 419, JUNTA AUXILIAR DE SAN AGUSTÍN CALVARIO, MUNICIPIO DE SAN PEDRO CHOLULA, PUEBLA.', 4, N'https://maps.app.goo.gl/jeakX7k172HGZeNG8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (36, N'DEPOSITO DE VEHÍCULO HERMANOS ROLDAN S.A. DE C.V.', N'FABIÁN ROLDAN TELLO', N'correo', N'FABIÁN ROLDAN TELLO', N'2223645865, 2223204645, 2222474829, 2225693138, 22', N'CALLE PUEBLA ORIENTE NO. 220, JUNTA AUXILIAR DE SAN COSME TEXINTLA, SAN PEDRO CHOLULA, PUEBLA. C.P. 72767.', 4, N'https://maps.app.goo.gl/FVjj1P19Ag3c6S4f9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (37, N'MARÍA DE LOS ÁNGELES MORENO SÁNCHEZ', N'MARÍA DE LOS ÁNGELES MORENO SÁNCHEZ', N'correo', N'MARÍA DE LOS ÁNGELES MORENO SÁNCHEZ', N'2227065785', N'CALLE CHAMIZAL NO. 275, LOCALIDAD SAN FRANCISCO OCOTLÁN, MUNICIPIO DE CORONANGO, PUEBLA. C.P. 72680', 4, N'https://maps.app.goo.gl/Md7a2jKpf4HrVD6b9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (38, N'CARLOS LEAL LÓPEZ - GRÚAS LEAL', N'CARLOS LEAL LÓPEZ', N'correo', N'CARLOS LEAL LÓPEZ', N'9531321412, 9531002307', N'CARRETERA INTERNACIONAL KM. 155 + 300, CARRETERA XUCHIATE, BARRIO DE SAN CRISTÓBAL, ACATLÁN DE OSORIO PUEBLA.', 5, N'https://maps.app.goo.gl/wTWR2zF2K8WCXMzK7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (39, N'DAUDET SEIN LEAL LÓPEZ - GRÚAS LEAL LÓPEZ', N'DAUDET SEIN LEAL LÓPEZ', N'correo', N'DAUDET SEIN LEAL LÓPEZ', N'9531321412', N'CARRETERA INTERNACIONAL KILÓMETRO 156+800, CARRETERA MÉXICO- XUCHIATE, BARRIO SAN CRISTÓBAL, MUNICIPIO DE ACATLÁN DE OSORIO.', 5, N'https://maps.app.goo.gl/WqyVNuFz26CU8vhi6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (40, N'GRÚAS LANZAGORTA S.A. DE C.V.', N'ALBERTO EDUARDO LANZAGORTA ROMERO', N'correo', N'ALBERTO EDUARDO LANZAGORTA ROMERO', N'7767610062, 7767678308, 7712885816', N'KM. 103+600 DE LA CARRETERA FEDERAL NO. 119, APIZACO- TEJOCOTLA Y/O CAMINO VIEJO A BERISTAIN, ESQUINA CAMINO A LA ANTIGUA ESTACIÓN DEL FERROCARRIL EN LA LOCALIDAD DE AHUAZOTEPEC, PUEBLA.', 6, N'https://maps.app.goo.gl/S32pupJXE5XuL3ob8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (41, N'EVARISTO MORALES OSORIO - GRÚAS MORALES', N'EVARISTO MORALES OSORIO', N'correo', N'EVARISTO MORALES OSORIO', N'2444452054, 2226812140', N'CALLE 3 PONIENTE NO. 4101 ESQUINA CON 43 SUR, COLONIA RANCHO GAMBOA, MUNICIPIO DE ATLIXCO, PUEBLA.', 7, N'https://maps.app.goo.gl/9eGb3X8sF6JQrbD69', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (42, N'LUIS SALVADOR GARCÍA FLORES - GRÚAS PACHECO', N'LUIS SALVADOR GARCÍA FLORES', N'correo', N'LUIS SALVADOR GARCÍA FLORES', N'244450028, 2441001210, 2441064173', N'CAMINO DEL EJIDO LOTE 04, NO. 502, SAN FÉLIX HIDALGO, ATLIXCO, PUEBLA Y OTRO PREDIO UBICADO EN BOULEVARD EMILIANO ZAPATA, NO. 305, COLONIA RICARDO FLORES MAGÓN, ATLIXCO', 7, N'https://maps.app.goo.gl/BuCEqPKV8RYqimULA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (43, N'GRÚAS ASSIAUTO, S.A. DE C.V.', N'ENRIQUE GÁMEZ MENDOZA', N'correo', N'ENRIQUE GÁMEZ MENDOZA', N'2441080516, 2441080585, 2446887507', N'CALLE CARMEN SERDÁN NO. 10, COLONIA REVOLUCIÓN DEL MUNICIPIO DE ATLIXCO, PUEBLA C.P. 74270. CALLE IGNACIO ZARAGOZA NO. 6 ROTONDA DE TEHUIXPANGO, PUEBLA C.P. 74367', 7, N'https://maps.app.goo.gl/xM6XriacGhD1wfrF7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (44, N'ZACARÍAS JAVIER LOYOLA EVANGELISTA - GRÚAS LOYOLA', N'ZACARÍAS JAVIER LOYOLA EVANGELISTA', N'correo', N'ZACARÍAS JAVIER LOYOLA EVANGELISTA', N'2441060671, 2226165830, 2227394469', N'CALLE BRECHA NO. 301 SANTA ANA OCOZAUTLA, SANTA ISABEL CHOLULA, PUEBLA.', 7, N'https://maps.app.goo.gl/DuvPrBKMu6TFicic9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (45, N'NEMORIO GONZÁLEZ FLORES - ENCIERRO VEHICULAR SERVICIO DE GRÚAS GONZÁLEZ Y TECALI', N'NEMORIO GONZÁLEZ FLORES', N'correo', N'NEMORIO GONZÁLEZ FLORES', N'2225362331, 2226505101', N'CARRETERA VALSEQUILLO TECALI-KILOMETRO 3, SAN BALTAZAR TORIJA, PUEBLA. CARRETA ESTATAL SAN JOSE MORELOS CUAUTINCHAN SIN NUMERO', 8, N'https://maps.app.goo.gl/zeWcEwFwFxLiSf566', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (46, N'GABINO GIL NAVARRETE - GRÚAS GIL', N'GABINO GIL NAVARRETE', N'correo', N'GABINO GIL NAVARRETE', N'2751036501', N'AV. UNIVERSIDAD No. 4, COLONIA EL RETIRO,CHIAUTLA DE TAPIA, PUE.', 9, N'https://maps.app.goo.gl/9zNU12HkE3agGY599', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (47, N'ZACARÍAS JAVIER LOYOLA EVANGELISTA - GRÚAS LOYOLA', N'ZACARÍAS JAVIER LOYOLA EVANGELISTA', N'correo', N'ZACARÍAS JAVIER LOYOLA EVANGELISTA', N'2441060671, 2441446478', N'DIRECCIÓN DE DEPÓSITO Y PARA RECIBIR NOTIFICACIONES: LIBRAMIENTO IZÚCAR-ATENCINGO NO. 15 TEMAXCALAPA DE GAINO BARREDA, MUNICIPIOP DE CHIETLA, PUEBLA, C.P. 74580', 10, N'https://maps.app.goo.gl/9PN4B76kjkvWSvqt9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (48, N'EDGAR CONTRERAS PÉREZ - GRÚAS BOCHO´S Y JUNIOR´S', N'EDGAR CONTRERAS PÉREZ', N'correo', N'EDGAR CONTRERAS PÉREZ', N'2381424326, 2381663787,2454566240', N'CARRETERA ESTATAL CIUDAD SERDÁN-SAN PEDRO EN EL EJIDO SANTA MARÍA TECHACHALCO NO. DE PARCELA 74 Z-1P1/2º, MUNICIPIO DE CHALCHICOMULA DE SESMA, CIUDAD SERDÁN PUEBLA.', 11, N'https://maps.app.goo.gl/56VCAEt2hj39E52SA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (49, N'SERVICIOS ESPECIALIZADOS SERDÁN, S.A. DE C.V.', N'JULIO CESAR FLORES BALCÁZAR', N'correo', N'JULIO CESAR FLORES BALCÁZAR', N'2454504148, 2454521041, 2454522875', N'KILOMETRO 28 S/N CARRETERA FEDERAL EL SECO- ESPERANZA, CHALCHICOMULA DE SESMA, CIUDAD SERDÁN, PUEBLA.', 11, N'https://maps.app.goo.gl/y761TkMJxETaxxqr9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (50, N'MARÍA GUADALUPE GARCÍA BOLAÑOS - GRÚAS SERDÁN', N'MARÍA GUADALUPE GARCÍA BOLAÑOS', N'correo', N'MARÍA GUADALUPE GARCÍA BOLAÑOS', N'2454521041', N'KM. 25+200 DE LA CARRETERA FEDERAL EL SECO-ESPERANZA, CHALCHICOMULA DE SESMA, CIUDAD SERDÁN, PUEBLA C.P. 75520.', 11, N'https://maps.app.goo.gl/yRt65XNhEq3sebFr8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (51, N'SONIA ELIZABETH VILLALOBOS TAVERA - GRÚAS HEMS', N'SONIA ELIZABETH VILLALOBOS TAVERA', N'correo', N'SONIA ELIZABETH VILLALOBOS TAVERA', N'2213445344, 2451180017, 2451155607, 2456880052', N'CARRETERA FEDERAL SAN SALVADOR EL SECO-AZUMBILLA KM. 28+000 EN EL EJIDO DE CIUDAD SERDÁN NO. 1055 Z-1P1/2, MUNICIPIO DE CHALCHICOMULA DE SESMA, PUEBLA.', 11, N'https://maps.app.goo.gl/ZUWmMabWsX9HMfLa7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (52, N'ILCE GISELA MENDOZA REYES - GRÚAS CHIGNAHUAPAN', N'ILCE GISELA MENDOZA REYES', N'correo', N'ILCE GISELA MENDOZA REYES', N'7971252588, 7971252588', N'CALLE AGUSTIN MELGAR NO. 4 BARRIO DE TOLTEMPAN, CHIGNAHUAPAN PUEBLA.', 12, N'https://maps.app.goo.gl/aeN5rffKp9vrysWL8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (53, N'RAMIRO ALONSO BUENO - GRÚAS ALONSO', N'RAMIRO ALONSO BUENO', N'correo', N'RAMIRO ALONSO BUENO', N'2271000209, 2224445306, 2225983782', N'CARRETERA FEDERAL MÉXICO-PUEBLA KM. 85.3 S/N COLONIA TERCER BARRIO, HUEJOTZINGO PUEBLA. C.P. 74160.', 12, N'https://maps.app.goo.gl/7dyjbzdzkgwrA2gMA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (54, N'LEONARDO ORDAZ PANECATL - GRÚAS EBEN EZER', N'LEONARDO ORDAZ PANECATL', N'correo', N'LEONARDO ORDAZ PANECATL', N'2227058414, 2228134854, 2227065785, 2222080535', N'CARRETERA AEROPUERTO HERMANOS SERDÁN-HUEJOTZINGO NO. 2728, HUEJOTZINGO, PUEBLA.', 12, N'https://maps.app.goo.gl/BHziR46BZLitT1eWA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (55, N'LIZBETH ALONSO JÍMENEZ', N'LIZBETH ALONSO JÍMENEZ', N'correo', N'LIZBETH ALONSO JÍMENEZ', N'2225983782', N'PROLONGACIÓN LEONA VICARIO 3132 COLONIA SANTA ELENA 3ER BARRIO HUEJOTZINGO, PUE.', 12, N'https://maps.app.goo.gl/GryYnXYjbvTRj2Dw8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (56, N'ALBERTO MORENO SÁNCHEZ - GRÚAS Y MANIOBRAS YAHVE', N'ALBERTO MORENO SÁNCHEZ', N'correo', N'ALBERTO MORENO SÁNCHEZ', N'2484887577', N'CARRETERA FEDERAL MEX-PUE KM. 80 SANTA MARÍA MOYOTZINGO, SAN MARTÍN TEXMELUCAN', 12, N'https://maps.app.goo.gl/cr55VXaqWoZ6fd7YA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (57, N'ÁLVARO JESÚS GALLEGOS MACÍAS - GRÚAS GALLEGOS', N'ÁLVARO JESÚS GALLEGOS MACÍAS 4556 M2 FEDERAL', N'correo', N'ÁLVARO JESÚS GALLEGOS MACÍAS 4556 M2 FEDERAL', N'776112389', N'DIRECCIÓN DE DEPÓSITO Y PARA RECIBIR NOTIFICACIONES: CAMINO A XATEPE S/N, COLONIA CUACUILA, HUAUCHINANGO, PUEBLA.', 13, N'https://maps.app.goo.gl/FQQnWreZsZv41rtX8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (58, N'ARTURO ROMÁN GUZMÁN ARREOLA - GRÚAS GUZMÁN', N'ARTURO ROMÁN GUZMÁN ARREOLA', N'correo', N'ARTURO ROMÁN GUZMÁN ARREOLA', N'2431092524, 2431095226', N'EMILIO CARRANZA NO. 199, BARRIO DE SANTIAGO MIHUACAN, IZÚCAR DE MATAMOROS PUEBLA.', 14, N'https://maps.app.goo.gl/SdGgsC1Vs2fjLNyv9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (59, N'GRÚAS LA VILLA RICA S.A. de C.V.', N'EMETERIO MARTÍNEZ RIVERA', N'correo', N'EMETERIO MARTÍNEZ RIVERA', N'2434363831, 2434364483, 2436881309, 2434350538', N'KM. 193.5 CARRETERA MÉXICO SUCHIATE, COLONIA SAN MARTÍN ALCHICHICA, IZUCAR DE MATAMOROS, PÚEBLA. C.P. 74570', 14, N'https://maps.app.goo.gl/Y4FqLFtZ21AKbkGLA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (60, N'EMETERIO MARTÍNEZ RIVERA - GRÚAS IZÚCAR', N'EMETERIO MARTÍNEZ RIVERA', N'correo', N'EMETERIO MARTÍNEZ RIVERA', N'2434363831, 2344364483, 2434350538', N'CARRETERA MÉXICO-SUCHIATE KM. 193.5, COLONIA SAN MARTÍN ALCHICHICA, IZUCAR DE MATAMOROS, PÚEBLA. C.P. 74570', 14, N'https://maps.app.goo.gl/thXNdZjhQAQsAJ1r5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (61, N'JORGE LEYVA CARDOSO - GRÚAS LEYVA', N'JORGE LEYVA CARDOSO', N'correo', N'JORGE LEYVA CARDOSO', N'2431106122, 2434363085, 2436884053', N'CALLE 2 PONIENTE NÚMERO 136 AVENIDA COQUIXTLÁN NO. 138, ESQUINA CON CALLE LA MAGDALENA OJO DE AGUA, BARRIO DE LOS REYES, MUNICIPIO DE IZÚCAR DE MATAMOROS PUEBLA C.P. 74490', 15, N'https://maps.app.goo.gl/Vs6TduUtmnXZEgWo6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (62, N'GRUÁS BRETÓN DE LIBRES S.A. DE C.V.', N'OLAF BRETÓN LÓPEZ', N'correo', N'OLAF BRETÓN LÓPEZ', N'2764730025, 2761023839', N'CARRETERA FEDERAL No. 140, SAN HIPÓLITO XALAPA KM. 55+700, INTERIOR B, SAN JOSÉ ZACATEPEC, ORIENTE, PUEBLA. C.P. 75029', 16, N'https://maps.app.goo.gl/L3nMKuz4z7GDF3A58', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (63, N'GRÚAS CANTONA, S.A. DE C.V.', N'MANFRED BRETÓN LÓPEZ', N'correo', N'MANFRED BRETÓN LÓPEZ', N'2761002005, 2721529022', N'DIRECCIÓN DE DEPÓSITO Y PARA RECIBIR NOTIFICACIONES: CARRETERA FEDERAL MÉXICO- VERACRUZ KM 55+700, SAN JOSÉ ZACATEPEC, ORIENTAL, PUEBLA, C.P. 75029', 17, N'https://maps.app.goo.gl/zTGJfmPEEmymHPVHA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (64, N'NIDIA ALDUCIN HERNANDEZ - GRÚAS NIDIA ALDUCIN HERNANDEZ', N'NIDIA ADUCIN HERNANDEZ', N'correo', N'NIDIA ADUCIN HERNANDEZ', N'2494241388, 8008363313, 2494240476, 2491192358, 24', N'CAMINO A RANCHO DE LOS HERMANOS LÓPEZ LIMA, S/N, MUNICIPIO DE PALMAR DE BRAVO, PUEBLA.', 18, N'https://maps.app.goo.gl/oqSHefdH8D2bYc5F6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (65, N'MARÍA ANGÉLICA GARCÍA CARVAJAL - DEPÓSITO VEHICULAR GRÚAS JOE', N'MARÍA ANGÉLICA GARCÍA CARVAJAL', N'correo', N'MARÍA ANGÉLICA GARCÍA CARVAJAL', N'2227500232, 2224077784, 2221790555, 2225695121', N'CAMINO ANTIGUO A SANTA ISABEL No. 23-1, SANTA ANAN ACOZAUTLA,SANTA ISABEL CHOLULA, PUEBLA. C.P. 74358.', 19, N'https://maps.app.goo.gl/TscvDEzYcBXQGc9v5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (66, N'RUFINA CAMILO PÉREZ - GRÚAS LEONCAMI', N'RUFINA CAMILO PÉREZ', N'correo', N'RUFINA CAMILO PÉREZ', N'2481156362, 2484845307', N'LIBRAMIENTO, PREDIO EL POTRERO SAN JUAN TUXCO SAN MARTÍN TEXMELUCAN.', 20, N'https://maps.app.goo.gl/4D7DRf1LPq2qx8JL6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (67, N'RAÚL PÉREZ ISLAS - GRÚAS ISLAS', N'RAÚL PÉREZ ISLAS', N'correo', N'RAÚL PÉREZ ISLAS', N'2481022366, 2482018171, 2481016279', N'CALLE HIDALGO NO. 125 SAN LUCAS ATOYATENCO, SAN MARTÍN TEXMELUCAN.MEDIANTE LLAMADA CAMBIO EL DOMICILIO DEL DEPOSITO ALBINO LABASTIDA', 20, N'https://maps.app.goo.gl/TBz5P4FyPQunpRWH6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (68, N'MANUEL LUNA ROMERO - GRÚAS LOGÍSTICOS DEL SUR', N'MANUEL LUNA ROMERO', N'correo', N'MANUEL LUNA ROMERO', N'5611745673', N'DIRECCIÓN DE DEPÓSITO Y PARA RECIBIR NOTIFICACIONES: CALLE INDEPENDENCIA NO. 125 COLONIA JOYAS DE SAN DAMIÁN, SAN MARTÍN TEXMELUCAN, PUEBLA.', 20, N'https://maps.app.goo.gl/RcVFDjzKQBYvtpDV9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (69, N'JOSÉ RODOLFO MORENO ROLDÁN', N'JOSE RODOLFO MORENO ROLDAN', N'correo', N'JOSE RODOLFO MORENO ROLDAN', N'2222128899', N'Dirección de Depósito: PREDIO CONOCIDO COMO EX EJIDO SANTA CATARINA HUEYATZACUALCO, SAN MARTIN TEXMELUCAN, PUEBLA.', 20, N'https://maps.app.goo.gl/YietTHZkdqW9JzGPA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (70, N'EMMANUEL LAYIDUA ESTRADA GARCÍA - GRÚAS ESTRADA', N'EMMANUEL LAYIDUA ESTRADA GARCÍA', N'correo', N'EMMANUEL LAYIDUA ESTRADA GARCÍA', N'2482704752', N'DIRECCIÓN DE DEPÓSITO Y PARA RECIBIR NOTIFICACIONES: CAMINO A BARRANCA DE PESOS NO. 215 SAN LUCAS ATOYATENCO, SAN MARTIN TEXMELUCAN, PUE.', 20, N'https://maps.app.goo.gl/VeZAfeBfMBjiM8BY6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (71, N'NEOTALIN PÉREZ OLMOS - GRÚAS OLMOS', N'NEOTALIN PÉREZ OLMOS', N'correo', N'NEOTALIN PÉREZ OLMOS', N'2481016279, 2484820861', N'Dirección de Depósito y para recibir notificaciones: CARRETERA AL VERDE KM. 6.5 SAN GREGORIO AZTOTOACAN, SAN SALVADOR EL VERDE, PUEBLA. C.P. 74130', 20, N'https://maps.app.goo.gl/KrngENT9svvjWLLN9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (72, N'JAVIER HUERTA MONTERO - GRÚAS TLAHUAPAN', N'JAVIER HUERTA MONTERO', N'correo', N'JAVIER HUERTA MONTERO', N'2481250819, 2481019524, 2481438326', N'Dirección de Depósito: CARRETERA A SAN SALVADOR EL VERDE No. 24, COLONIA SAN CAYETANO MUNICIPIO DE TLAHUAPAN, PUEBLA. C.P. 74100.', 20, N'https://maps.app.goo.gl/dUSDsgcqYDPQ15KD7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (73, N'DESPLAZAMIENTO ESPECIALIZADOS EN ASISTENCIA, S.A. DE C.V. DEA', N'JUAN MANUEL RODRÍGUEZ VICTORIA', N'correo', N'JUAN MANUEL RODRÍGUEZ VICTORIA', N'2225424751, 225619630, 2222490300, 2222490302, 222', N'DIRECCIÓN DE DEPÓSITO Y PARA RECIBIR NOTIFICACIONES: CAMINO A LAS CANTERAS S/N, SAN JUAN IXCAQUIXTLA, PUEBLA. C.P. 74900.', 21, N'https://maps.app.goo.gl/B5RuXB5LmBwcDoYbA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (74, N'GRÚAS MEXICANOS DE TEZIUTLAN, S.A. DE C.V.', N'JOVANNY BRETÓN LÓPEZ', N'correo', N'JOVANNY BRETÓN LÓPEZ', N'2313131676, 2313136717, 2311227827', N'SECCIÓN 2DA DE LA JUNTA AUXILIAR DE SAN DIEGO CARRETERA TEZIUTLÁN-SAN JUAN ACATENO KM. 7.5 HOY CALLE JOSEFA RAMIRO GALVILAN S/N TEZIUTLAN, PUEBLA.', 22, N'https://maps.app.goo.gl/9kSc2WY5S1WoHGVHA', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (75, N'GLORIA ESMERALDA RODRÍGUEZ CASTRO - GRÚAS PREMIUM', N'GLORIA ESMERALDA RODRÍGUEZ CASTRO', N'correo', N'GLORIA ESMERALDA RODRÍGUEZ CASTRO', N'2236880753', N'CALLE 5 ORIENTE No. 719, BARRIO DIVINO SALVADOR, MUNICIPIO DE TEPEACA, PUEBLA.', 23, N'https://maps.app.goo.gl/M99ui3JgUbT78V9X9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (76, N'FRANCISCO HERNÁNDEZ LOEZA', N'FRANCISCO HERNANDEZ LOEZA', N'correo', N'FRANCISCO HERNANDEZ LOEZA', N'2225999426', N'PARCELA 258 Z-1P/13 DEL EJIDO DE SAN LUIS AJALPA, TECALI DE HHERRERA, PUE. Y/O AVENIDA 5 DE MAYO SIN NÚMERO SAN LUIS AJAJALPA, PUEBLA CP 75250', 23, N'https://maps.app.goo.gl/dnKaTPT3Rqrvcwci9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (78, N'CESAR BERMÚDEZ ILLESCAS - GRÚAS OLIVER', N'CESAR BERMÚDEZ ILLESCAS', N'correo', N'CESAR BERMÚDEZ ILLESCAS', N'2381203305, 2381216820, 2381652877, 2381472886', N'DIRECCIÓN DE DEPÓSITO: CARRETERA ESTATAL TEHUACÁN-SAN GABRIEL CHILAC KM. 0+100, COLONIA GUADALUPE EN SAN PEDRO TEPETZINGO. DIRECCIÓN PARA RECIBIR NOTIFICACIONES: CALLE ESMERALDA NO. 1718 LETRA A FRACCIONAMIENTO LA CANTERA TEHUACÁN,PUEBLA ', 23, N'https://maps.app.goo.gl/PVrunmeigFXXPTKb6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (79, N'DAVID FLORES GARCÍA - GRÚAS ELITE', N'DAVID FLORES GARCÍA', N'correo', N'DAVID FLORES GARCÍA', N'2381506525, 2386883273, 2382352223', N'DIRECCIÓN DE DEPÓSITO: CALLE COAHUILA NO. 1702, COLONIA MÉXICO SUR, TEHUACÁN, PUEBLA. C.P. 75768 DIRECCIÓN PARA RECIBIR NOTIFICACIONES: CALLE 5 PONIENTE NO. 6205, COLONIA VENUSTIANO CARRANZA, TEHUACÁN PUEBLA.', 24, N'https://maps.app.goo.gl/3Ch2GDPtw7v3cSji8', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (80, N'RUBÉN GARCÍA BOLAÑOS - GRÚAS GARBO', N'RUBÉN GARCÍA BOLAÑOS', N'correo', N'RUBÉN GARCÍA BOLAÑOS', N'2381471486, 2383835005, 2382000819', N'DIRECCIÓN DE DEPÓSITO: CALLE COAHUILA NO. 1702, COLONIA MÉXICO SUR, TEHUACÁN, PUEBLA. C.P. 75768 DIRECCIÓN PARA RECIBIR NOTIFICACIONES: CALLE 5 PONIENTE NO. 6205, COLONIA VENUSTIANO CARRANZA,TEHUACÁN PUEBLA.', 24, N'https://maps.app.goo.gl/6C5rhPTGhbCzbwFM9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (81, N'MISAEL GARCÍA CRUZ - GRÚAS GARES ARRASTRE Y SALVAMENTOS', N'MISAEL GARCÍA CRUZ', N'correo', N'MISAEL GARCÍA CRUZ', N'2383806479, 2381874287', N'DIRECCIÓN DE DEPÓSITO: KM 37 AUTOPISTA CUACNOPALAN-OAXACA, EJDO FRANCISCO I. MADERO, TEPANCO DE LÓPEZ, PUEBLA.', 24, N'https://maps.app.goo.gl/AJZXQxtaUvNnMc688', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (82, N'LEOPOLDO GARCÍA GARCÍA - GRÚAS LA BARRANCA', N'LEOPOLDO GARCÍA GARCÍA', N'correo', N'LEOPOLDO GARCÍA GARCÍA', N'2361077405', N'CALLE RÍO TEHUACÁN NO. 1010, BARRIO COCULCO AJALPAN PUEBLA.', 24, N'https://maps.app.goo.gl/EL5W78DZZEfvSX2f9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (83, N'FRANCISCO DAVID LEYVA JUAREZ - GRÚAS JUQUILITA', N'FRANCISCO DAVID LEYVA JUÁREZ', N'correo', N'FRANCISCO DAVID LEYVA JUÁREZ', N'2381856468, 2371013473, 2381172608', N'ABASOLO ENTRE CALLE MATAMOROS Y CALLE GUERRERO, COLONIA CENTRO, LOCALIDAD DE SAN GABRIEL CHILAC, PUEBLA.', 24, N'https://maps.app.goo.gl/gZg1xRpemJQbzaT88', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (84, N'NAYELLI CEPEDA GARCÍA - GRÚAS 117', N'NAYELLI CEPEDA GARCÍA', N'correo', N'NAYELLI CEPEDA GARCÍA', N'2383052472', N'CALLE FERROCARRIL EX VÍA ANTIGUO A MIAHUATLAN S/N LOCALIDAD DE SAN VICENTE FERRER, MUNICIPIO DE TEHUACÁN C.P. 75710', 24, N'https://maps.app.goo.gl/rVQBfWiZEusYMejM9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (85, N'GUSTAVO GALINDO TELLEZ - GRÚAS DEL NORTE', N'GUSTAVO GALINDO TELLEZ', N'correo', N'GUSTAVO GALINDO TELLEZ', N'2333116089, 2333181581', N'CALLE HERMANOS SERDÁN No. 2, TLATLAUQUITEPEC, PUEBLA.', 25, N'https://maps.app.goo.gl/KHUfgRsu4KZdwmxu5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (86, N'ANDRÉS CEPEDA JIMÉNEZ - GRÚAS TEZIUTLAN', N'ANDRÉS CEPEDA JIMÉNEZ', N'correo', N'ANDRÉS CEPEDA JIMÉNEZ', N'22237340, 2222373441, 2313134064', N'CALLE MORELOS S/N COLONIA CALA SUR, MUNICIPIO DE ATEMPAN, PUEBLA.', 25, N'https://maps.app.goo.gl/njYsVfARbWm7zjRm7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (87, N'CARLOS CANO FERNÁNDEZ - GRÚAS XICO', N'CARLOS CANO FERNÁNDEZ', N'correo', N'CARLOS CANO FERNÁNDEZ', N'7971054410, 7979751209, 7641134148', N'KM. 113+000 DE LA CARRETERA MÉXICO-TUXPAN, COLONIA DOS CAMINOS, MUNICIPIO DE XICOTEPEC DE JUÁREZ, PUEBLA.', 26, N'https://maps.app.goo.gl/Gwp5uFEpLZ7bnKko9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (88, N'CESAR CANO FERNÁNDEZ - MULTISERVICIOS Y GRÚAS CANO', N'CESAR CANO FERNÁNDEZ', N'correo', N'CESAR CANO FERNÁNDEZ', N'7971097675, 7979751209', N'CALLE MATAMOROS No. 14 COLONIA ZACATZINGO ELOXOCHITLAN, ZACATLAN, PUEBLA. C.P. 73310', 27, N'https://maps.app.goo.gl/7KMQgHthKZe9tUsn9', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (89, N'ELIZABETH CRUZ CANO - GRÚAS CALÚ', N'ELIZABETH CRUZ CANO', N'correo', N'ELIZABETH CRUZ CANO', N'S/D', N'H. GALEANA No. 90 ZACATZINGO ELOXOCHITLAN, ZACATLAN, PUEBLA.', 27, N'https://maps.app.goo.gl/fQYFDcD82iPpkyss6', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (90, N'EMILIO LOBATO TORAL - GRÚAS ZACAPOAXTLA', N'EMILIO LOBATO TORAL', N'correo', N'EMILIO LOBATO TORAL', N'2333142677, 2331010706', N'SECCIÓN 4TA TENEXCAPILLA XALACAPAN ZACAPOAXTLA, PUEBLA.', 28, N'https://maps.app.goo.gl/emwVqgzr8MiTYGgy5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (91, N'TRASLADOS Y MANIOBRAS TELLEZ S.A. DE C.V.', N'ELÍAS TÉLLEZ GALINDO', N'correo', N'ELÍAS TÉLLEZ GALINDO', N'2333116116, 2337599583', N'KM. 113 CARRETERA FEDERAL AMOZOC-TEZIUTLÁN COLONIA MORELOS, ZARAGOZA, PUEBLA C.P. 73700', 29, N'https://maps.app.goo.gl/xjzmADYLRCE5H5Kt5', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
INSERT [dbo].[CatDepositoVehicular] ([Id], [RazonSocial], [RepresentanteLegal], [CorreoElectronicoContacto], [NombreCompletoContactos], [Telefonos], [DireccionDeposito], [RegionId], [Ubicacion], [Latitud], [Longitud], [CreadoPorAdminId], [FechaCreacion], [ActualizadoPorAdminId], [FechaActualizacion], [Activo]) VALUES (92, N'LUIS ÁNGEL CARRERA MÉNDEZ – GRÚAS CARRERA', N'LUIS ÁNGEL CARRERA MÉNDEZ', N'correo', N'LUIS ÁNGEL CARRERA MÉNDEZ', N'22275081582212200000', N'CALLE FRANCISCO VILLA NO.413, JUNTA AUXILIAR DE SAN FRANCISCO OCOTLÁN, MUNICIPIO DE CORONANGO, PUEBLA.', 1, N'https://maps.app.goo.gl/QKV8eMUBpwZ1MHCS7', NULL, NULL, 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1, CAST(N'2025-05-23T00:00:00.000' AS DateTime), 1)
GO
SET IDENTITY_INSERT [dbo].[CatDepositoVehicular] OFF
GO
