USE [DepositoVehicular_DB]
GO
UPDATE [dbo].[CatMunicipio] SET Regionid=1 WHERE Id=114
UPDATE [dbo].[CatMunicipio] SET Regionid=2 WHERE Id=15
UPDATE [dbo].[CatMunicipio] SET Regionid=3 WHERE Id=4
UPDATE [dbo].[CatMunicipio] SET Regionid=3 WHERE Id=96
UPDATE [dbo].[CatMunicipio] SET Regionid=3 WHERE Id=104
UPDATE [dbo].[CatMunicipio] SET Regionid=3 WHERE Id=152
UPDATE [dbo].[CatMunicipio] SET Regionid=3 WHERE Id=65
UPDATE [dbo].[CatMunicipio] SET Regionid=4 WHERE Id=34
UPDATE [dbo].[CatMunicipio] SET Regionid=4 WHERE Id=41
UPDATE [dbo].[CatMunicipio] SET Regionid=4 WHERE Id=119
UPDATE [dbo].[CatMunicipio] SET Regionid=4 WHERE Id=125
UPDATE [dbo].[CatMunicipio] SET Regionid=4 WHERE Id=140
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=3
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=9
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=55
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=59
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=66
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=112
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=113
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=127
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=135
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=139
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=141
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=155
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=190
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=191
UPDATE [dbo].[CatMunicipio] SET Regionid=5 WHERE Id=196
UPDATE [dbo].[CatMunicipio] SET Regionid=6 WHERE Id=8
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=19
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=5
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=22
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=52
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=31
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=33
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=69
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=70
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=150
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=106
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=159
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=175
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=185
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=188
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=121
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=138
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=146
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=165
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=148
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=102
UPDATE [dbo].[CatMunicipio] SET Regionid=7 WHERE Id=126
UPDATE [dbo].[CatMunicipio] SET Regionid=8 WHERE Id=40
UPDATE [dbo].[CatMunicipio] SET Regionid=8 WHERE Id=153
UPDATE [dbo].[CatMunicipio] SET Regionid=8 WHERE Id=193
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=47
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=11
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=24
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=56
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=32
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=73
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=81
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=87
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=157
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=160
UPDATE [dbo].[CatMunicipio] SET Regionid=9 WHERE Id=198
UPDATE [dbo].[CatMunicipio] SET Regionid=10 WHERE Id=51
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=45
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=12
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=23
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=50
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=58
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=63
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=93
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=116
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=137
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=179
UPDATE [dbo].[CatMunicipio] SET Regionid=11 WHERE Id=130
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=154
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=110
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=115
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=99
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=182
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=189
UPDATE [dbo].[CatMunicipio] SET Regionid=12 WHERE Id=205
UPDATE [dbo].[CatMunicipio] SET Regionid=13 WHERE Id=74
UPDATE [dbo].[CatMunicipio] SET Regionid=13 WHERE Id=60
UPDATE [dbo].[CatMunicipio] SET Regionid=13 WHERE Id=26
UPDATE [dbo].[CatMunicipio] SET Regionid=13 WHERE Id=90
UPDATE [dbo].[CatMunicipio] SET Regionid=13 WHERE Id=136
UPDATE [dbo].[CatMunicipio] SET Regionid=13 WHERE Id=181
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=85
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=7
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=21
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=42
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=62
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=133
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=166
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=168
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=176
UPDATE [dbo].[CatMunicipio] SET Regionid=14 WHERE Id=201
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=94
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=83
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=44
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=105
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=212
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=108
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=67
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=117
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=128
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=142
UPDATE [dbo].[CatMunicipio] SET Regionid=15 WHERE Id=170
UPDATE [dbo].[CatMunicipio] SET Regionid=16 WHERE Id=132
UPDATE [dbo].[CatMunicipio] SET Regionid=16 WHERE Id=48
UPDATE [dbo].[CatMunicipio] SET Regionid=16 WHERE Id=122
UPDATE [dbo].[CatMunicipio] SET Regionid=16 WHERE Id=143
UPDATE [dbo].[CatMunicipio] SET Regionid=16 WHERE Id=134
UPDATE [dbo].[CatMunicipio] SET Regionid=16 WHERE Id=180
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=82
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=37
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=95
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=98
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=131
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=147
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=169
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=206
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=20
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=79
UPDATE [dbo].[CatMunicipio] SET Regionid=17 WHERE Id=171
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=22
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=2
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=17
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=25
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=54
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=76
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=158
UPDATE [dbo].[CatMunicipio] SET Regionid=18 WHERE Id=199
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=164
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=1
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=38
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=118
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=97
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=151
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=144
UPDATE [dbo].[CatMunicipio] SET Regionid=19 WHERE Id=163
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=156
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=10
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=13
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=18
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=27
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=46
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=36
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=35
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=61
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=92
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=103
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=149
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=120
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=124
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=129
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=145
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=161
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=177
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=195
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=203
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=209
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=214
UPDATE [dbo].[CatMunicipio] SET Regionid=20 WHERE Id=217
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=186
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=75
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=204
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=207
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=80
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=28
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=29
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=30
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=43
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=77
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=84
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=88
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=101
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=162
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=192
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=200
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=202
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=210
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=215
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=216
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=211
UPDATE [dbo].[CatMunicipio] SET Regionid=21 WHERE Id=173
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=197
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=64
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=68
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=57
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=86
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=89
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=91
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=111
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=187
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=178
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=100
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=109
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=194
UPDATE [dbo].[CatMunicipio] SET Regionid=22 WHERE Id=213
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=208
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=6
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=14
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=39
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=72
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=78
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=107
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=123
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=167
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=16
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=172
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=53
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=71
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=49
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=183
UPDATE [dbo].[CatMunicipio] SET Regionid=23 WHERE Id=184
GO

